In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [105]:
df_gunung = pd.read_csv('/content/drive/My Drive/dataset/datagunung_lvl.csv',delimiter=',')
df_gunung = df_gunung.rename(columns={"Id": "mountain_id"})
df_gunung.head()

mountain_id     Daerah             Nama_Gunung  Ketinggian   \
0          101  Jawa barat          Gunung Cermai        3,078   
1          102  Jawa barat          Gunung Puntang       2,223   
2          103  Jawa barat      Gunung Papandayan        2,666   
3          104  Jawa barat  Gunung Gede Pangrango        2,958   
4          105  Jawa barat        Gunung Pangrango       3,019   

                               Lokasi            Trek  \
0  Kuningan, Majalengka, dan Cirebon.    Tanah Kering   
1                         Kab. Bandung   Tanah kering   
2                          Kab. Garut.      bebatuan    
3                                Bogor  Tangga Buatan   
4                              Cibodas   Akar Pohon     

                                          Jalur  Simaksi   Level  
0  Jalur Apuy, Linggarjati dan Jalur Palutungan  Rp30.000      1  
1                                             -  Rp40.000      1  
2                                             -  Rp60.000      1  
3                Jalur Cibodas dan Jalur Putri   Rp75.000      1  
4                                 Jalur Cibodas  Rp75.000      2

In [4]:
df_gunung.shape

(17, 9)

In [5]:
df_user = pd.read_csv('/content/drive/My Drive/dataset/MOCK_DATA.csv',delimiter=',')
df_user.head()

Id                 Nama                         Email      Password  \
0   1  Harcourt Leppington    hleppington0@reference.com        Zjvy1t   
1   2         Cristi Weeds     cweeds1@blogtalkradio.com     GRjASvqhv   
2   3        Thorny Gidden  tgidden2@acquirethisname.com  hTBgDny2C2p7   
3   4     Thibaut Spurdens       tspurdens3@omniture.com     aUz4mmfRq   
4   5      Cristionna Gaul            cgaul4@storify.com       5dU6hdn   

     Domisili Jenis Kelamin  Umur  Pengalaman  
0  Yogyakarta     Perempuan    24          12  
1     Cilacap     Laki-laki    18           5  
2    Semarang     Perempuan    48           9  
3     Cilacap     Perempuan    54          10  
4      Malang     Laki-laki    61          18

In [106]:
df_rating = pd.read_csv('/content/drive/My Drive/dataset/rating_data.csv',delimiter=',')
df_rating['mountain_id'] = df_rating['mountain_id']+100 
df_rating.head()

user_id  mountain_id  rating
0      284          113       2
1       33          111       5
2      167          108       1
3      623          105       5
4      378          110       1

In [107]:
mountain_id = df_rating['mountain_id']
# List of conditions
conditions = [
    (mountain_id == 101),
    (mountain_id == 102),
    (mountain_id == 103),
    (mountain_id == 104),
    (mountain_id == 105),
    (mountain_id == 106),
    (mountain_id == 107),
    (mountain_id == 108),
    (mountain_id == 109),
    (mountain_id == 110),
    (mountain_id == 111),
    (mountain_id == 112),
    (mountain_id == 113),
    (mountain_id == 114),
    (mountain_id == 115),
    (mountain_id == 116),
    (mountain_id == 117)]
# List of values to return
choices  = [
    "Gunung Cermai",
    "Gunung Puntang",
    "Gunung Papandayan",
    "Gunung Gede",
    "Gunung Pangrango",
    "Gunung Cikuray",
    "Gunung Prau",
    "Gunung Merbabu",
    "Gunung Sindoro",
    "Gunung Slamet",
    "Gunung Sumbing",
    "Gunung Arjuno",
    "Gunung Argopuro",
    "Gunung Lawu",
    "Gunung Semeru",
    "Gunung Raung",
    "Gunung Panderman",
    
]
# create a new column in the DF based on the conditions
df_rating.insert(2, 'mount_name', np.select(conditions, choices, "ERROR")) 

In [108]:
mountain_id = df_rating['mountain_id']
# List of conditions
conditions = [
    (mountain_id == 101),
    (mountain_id == 102),
    (mountain_id == 103),
    (mountain_id == 104),
    (mountain_id == 105),
    (mountain_id == 106),
    (mountain_id == 107),
    (mountain_id == 108),
    (mountain_id == 109),
    (mountain_id == 110),
    (mountain_id == 111),
    (mountain_id == 112),
    (mountain_id == 113),
    (mountain_id == 114),
    (mountain_id == 115),
    (mountain_id == 116),
    (mountain_id == 117)]
# List of values to return
choices  = [
    1,1,1,1,2,1,1,2,2,2,3,3,3,2,3,3,2
    
]
# create a new column in the DF based on the conditions
df_rating.insert(3, 'level', np.select(conditions, choices, "ERROR")) 

In [109]:
df_rating = df_rating.sort_values(['mountain_id']).reset_index(drop=True)
df_rating.head(15)

user_id  mountain_id     mount_name level  rating
0       210          101  Gunung Cermai     1       4
1       851          101  Gunung Cermai     1       4
2       760          101  Gunung Cermai     1       1
3       723          101  Gunung Cermai     1       5
4       660          101  Gunung Cermai     1       1
5       725          101  Gunung Cermai     1       2
6       844          101  Gunung Cermai     1       2
7       450          101  Gunung Cermai     1       5
8       520          101  Gunung Cermai     1       5
9       513          101  Gunung Cermai     1       5
10      353          101  Gunung Cermai     1       5
11      832          101  Gunung Cermai     1       5
12      597          101  Gunung Cermai     1       1
13      485          101  Gunung Cermai     1       3
14       47          101  Gunung Cermai     1       2

In [88]:
df_rating = df_rating.sort_values(['user_id']).reset_index(drop=True)
print(df_rating.head())
print(df_rating.shape)


   user_id  mountain_id        mount_name level  rating
0        1          113   Gunung Argopuro     3       1
1        1          112     Gunung Arjuno     3       2
2        1          109    Gunung Sindoro     2       1
3        1          117  Gunung Panderman     2       4
4        2          109    Gunung Sindoro     2       4
(5000, 5)


In [42]:
avg_mount_rate = df_rating.groupby(['mountain_id']).mean()
avg_mount_rate = avg_mount_rate.drop(['user_id'],axis=1)
avg_mount_rate = avg_mount_rate.sort_values(['rating'], ascending=False)
avg_mount_rate.head()

<ipython-input-42-6b694f445c44>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  avg_mount_rate = df_rating.groupby(['mountain_id']).mean()


rating
mountain_id          
117          3.190000
114          3.151724
103          3.104418
107          3.048544
101          3.045752

In [44]:
avg_mount_rate.shape

(17, 1)

In [45]:
import tensorflow as tf

In [122]:
tf_rating = tf.data.Dataset.from_tensor_slices(dict(df_rating))
tf_gunung = tf.data.Dataset.from_tensor_slices(dict(df_gunung))

In [123]:
# get the first rows of the movies dataset
for m in tf_gunung.take(5):
  print(m)

{'mountain_id': <tf.Tensor: shape=(), dtype=int64, numpy=101>, 'Daerah ': <tf.Tensor: shape=(), dtype=string, numpy=b'Jawa barat'>, 'Nama_Gunung ': <tf.Tensor: shape=(), dtype=string, numpy=b'Gunung Cermai '>, 'Ketinggian ': <tf.Tensor: shape=(), dtype=string, numpy=b'3,078'>, 'Lokasi ': <tf.Tensor: shape=(), dtype=string, numpy=b'Kuningan, Majalengka, dan Cirebon. '>, 'Trek': <tf.Tensor: shape=(), dtype=string, numpy=b'Tanah Kering'>, 'Jalur': <tf.Tensor: shape=(), dtype=string, numpy=b'Jalur Apuy, Linggarjati dan Jalur Palutungan'>, 'Simaksi ': <tf.Tensor: shape=(), dtype=string, numpy=b'Rp30.000'>, 'Level': <tf.Tensor: shape=(), dtype=int64, numpy=1>}
{'mountain_id': <tf.Tensor: shape=(), dtype=int64, numpy=102>, 'Daerah ': <tf.Tensor: shape=(), dtype=string, numpy=b'Jawa barat'>, 'Nama_Gunung ': <tf.Tensor: shape=(), dtype=string, numpy=b'Gunung Puntang'>, 'Ketinggian ': <tf.Tensor: shape=(), dtype=string, numpy=b'2,223'>, 'Lokasi ': <tf.Tensor: shape=(), dtype=string, numpy=b'Kab.

In [124]:
ratings = tf_rating.map(lambda x: {
    "mount_name": x["mount_name"],
    "user_id": x["user_id"]
})
gunung = tf_gunung.map(lambda x: x["Nama_Gunung "])

In [125]:
tf.random.set_seed(42)
shuffled = ratings.shuffle(100_000, seed=42, reshuffle_each_iteration=False)

train = shuffled.take(80_000)
test = shuffled.skip(80_000).take(20_000)

In [129]:
test.__len__()

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [130]:
user_ids_vocabulary = tf.keras.layers.IntegerLookup(mask_token=None)
user_ids_vocabulary.adapt(ratings.map(lambda x: x["user_id"]))
 
 
gunung_name_vocabulary = tf.keras.layers.StringLookup(mask_token=None)
gunung_name_vocabulary.adapt(gunung)

In [62]:
!pip install -q tensorflow-recommenders

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.2/96.2 kB 4.0 MB/s eta 0:00:00


In [115]:
from typing import Dict, Text
 
import tensorflow_recommenders as tfrs 

In [131]:
class GunungModel(tfrs.Model):
  # We derive from a custom base class to help reduce boilerplate. Under the hood,
  # these are still plain Keras Models.
 
  def __init__(
      self,
      user_model: tf.keras.Model,
      gunung_model: tf.keras.Model,
      task: tfrs.tasks.Retrieval):
    super().__init__()
 
    # Set up user and movie representations.
    self.user_model = user_model
    self.gunung_model = gunung_model
 
    # Set up a retrieval task.
    self.task = task
 
  def compute_loss(self, features: Dict[Text, tf.Tensor], training=False) -> tf.Tensor:
    # Define how the loss is computed.
 
    user_embeddings = self.user_model(features["user_id"])
    gunung_embeddings = self.gunung_model(features["mount_name"])
 
    return self.task(user_embeddings, gunung_embeddings)

In [132]:
# Define user and movie models.
user_model = tf.keras.Sequential([
    user_ids_vocabulary,
    tf.keras.layers.Embedding(user_ids_vocabulary.vocabulary_size(), 64)
])
gunung_model = tf.keras.Sequential([
    gunung_name_vocabulary,
    tf.keras.layers.Embedding(gunung_name_vocabulary.vocabulary_size(), 64)
])
 
# Define your objectives.
task = tfrs.tasks.Retrieval(metrics=tfrs.metrics.FactorizedTopK(
    gunung.batch(128).map(gunung_model)
  )
)

In [133]:
cached_train = train.shuffle(100_000).batch(8192).cache()
cached_test = test.batch(4096).cache()

In [136]:
cached_train.__len__()

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [137]:
# Create a retrieval model.
model = GunungModel(user_model, gunung_model, task)
model.compile(optimizer=tf.keras.optimizers.Adagrad(0.1))
 
# Train for 3 epochs.
model.fit(cached_train, epochs=3)

Epoch 1/3
1/1 [==============================] - 2s 2s/step - factorized_top_k/top_1_categorical_accuracy: 0.0342 - factorized_top_k/top_5_categorical_accuracy: 0.2596 - factorized_top_k/top_10_categorical_accuracy: 0.5430 - factorized_top_k/top_50_categorical_accuracy: 1.0000 - factorized_top_k/top_100_categorical_accuracy: 1.0000 - loss: 42586.1562 - regularization_loss: 0.0000e+00 - total_loss: 42586.1562
Epoch 2/3
1/1 [==============================] - 0s 343ms/step - factorized_top_k/top_1_categorical_accuracy: 0.1874 - factorized_top_k/top_5_categorical_accuracy: 0.6346 - factorized_top_k/top_10_categorical_accuracy: 0.7880 - factorized_top_k/top_50_categorical_accuracy: 1.0000 - factorized_top_k/top_100_categorical_accuracy: 1.0000 - loss: 42499.8711 - regularization_loss: 0.0000e+00 - total_loss: 42499.8711
Epoch 3/3
1/1 [==============================] - 0s 340ms/step - factorized_top_k/top_1_categorical_accuracy: 0.2952 - factorized_top_k/top_5_categorical_accuracy: 0.8538 - 

In [121]:
cached_test.__len__()

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [138]:
model.evaluate(ratings.batch(40), return_dict=True)

125/125 [==============================] - 6s 43ms/step - factorized_top_k/top_1_categorical_accuracy: 0.2964 - factorized_top_k/top_5_categorical_accuracy: 0.8680 - factorized_top_k/top_10_categorical_accuracy: 0.9016 - factorized_top_k/top_50_categorical_accuracy: 1.0000 - factorized_top_k/top_100_categorical_accuracy: 1.0000 - loss: 146.8842 - regularization_loss: 0.0000e+00 - total_loss: 146.8842


{'factorized_top_k/top_1_categorical_accuracy': 0.2964000105857849,
 'factorized_top_k/top_5_categorical_accuracy': 0.8679999709129333,
 'factorized_top_k/top_10_categorical_accuracy': 0.9016000032424927,
 'factorized_top_k/top_50_categorical_accuracy': 1.0,
 'factorized_top_k/top_100_categorical_accuracy': 1.0,
 'loss': 147.55517578125,
 'regularization_loss': 0,
 'total_loss': 147.55517578125}

In [145]:
# Use brute-force search to set up retrieval using the trained representations.
index = tfrs.layers.factorized_top_k.BruteForce(model.user_model)
index.index_from_dataset(
    gunung.batch(100).map(lambda title: (title, model.gunung_model(title))))
 
# Get some recommendations.
_, mountain_id = index(np.array([2]))
print(f"Top 10 recommendations for user 1: {mountain_id[0, :10]}")

Top 10 recommendations for user 1: [b'Gunung Arjuno' b'Gunung Merbabu' b'Gunung Sindoro' b'Gunung Semeru'
 b'Gunung Gede Pangrango ' b'Gunung Cikuray ' b'Gunung Prau '
 b'Gunung Cermai ' b'Gunung Papandayan ' b'Gunung Argupuro']
